services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: sui_hero
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: