version: '3.8'
services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: hero-js-indexer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: